// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";

export type BaseStats = { count: bigint, missing: bigint, distinct_estimate: bigint, inferred_type: DataType, };
