// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreqEntry } from "./FreqEntry";

export type CategoricalStats = { top_values: Array<FreqEntry>, unique_count: bigint, };
