// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseStats } from "./BaseStats";
import type { CategoricalStats } from "./CategoricalStats";
import type { ColumnQualityMetrics } from "./ColumnQualityMetrics";
import type { Histogram } from "./Histogram";
import type { NumericStats } from "./NumericStats";

export type ColumnProfile = { name: string, base_stats: BaseStats, numeric_stats: NumericStats | null, categorical_stats: CategoricalStats | null, histogram: Histogram | null, min_length: number | null, max_length: number | null, notes: Array<string>, quality_metrics: ColumnQualityMetrics | null, integer_count: bigint, numeric_count: bigint, boolean_count: bigint, date_count: bigint, total_valid: bigint, sample_values: Array<string>, missing_rows: Array<number>, pii_rows: Array<number>, outlier_rows: Array<number>, };
