// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of correlation matrix computation
 */
export type CorrelationMatrix = { 
/**
 * Names of numeric columns included in the correlation matrix
 */
columns: Array<string>, 
/**
 * NxN matrix of Pearson correlation coefficients
 * matrix[i][j] is correlation between columns[i] and columns[j]
 */
matrix: Array<Array<number>>, };
