// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumericStats = { min: number, max: number, mean: number, sum: number, count: bigint, std_dev: number, variance: number, skewness: number, kurtosis: number, median: number, p25: number, p75: number, p90: number, p95: number, p99: number, };
