// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnProfile } from "./ColumnProfile";
import type { QualityIssue } from "./QualityIssue";

export type ProfilerResult = { column_profiles: Array<ColumnProfile>, total_rows: bigint, duplicate_issues: Array<QualityIssue>, avro_schema: string | null, };
