// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type QualityIssue = { id: string, message: string, severity: Severity, };
