import { ProfileResult } from '../stores/profileStore';

/**
 * JSON Schema Draft 2020-12 Export
 *
 * Generates a valid JSON Schema document from DataCert profile results.
 * Used for data validation in any JSON Schema-compatible tool.
 *
 * Type Mapping:
 * - Integer -> "integer" with minimum/maximum
 * - Numeric -> "number" with minimum/maximum
 * - String -> "string" with minLength/maxLength
 * - Boolean -> "boolean"
 * - Date -> "string" with format: "date"
 * - DateTime -> "string" with format: "date-time"
 * - Mixed -> ["string", "number", "boolean", "null"]
 * - Null/Empty -> "null"
 */

interface JsonSchemaProperty {
  type: string | string[];
  description?: string;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  format?: string;
}

interface JsonSchema {
  $schema: string;
  $id: string;
  title: string;
  description: string;
  type: 'object';
  properties: Record<string, JsonSchemaProperty>;
  required: string[];
}

/**
 * Maps DataCert inferred types to JSON Schema types
 */
function mapDataCertTypeToJsonSchema(
  inferredType: string
): { type: string | string[]; format?: string } {
  const typeMapping: Record<string, { type: string | string[]; format?: string }> = {
    Integer: { type: 'integer' },
    Numeric: { type: 'number' },
    String: { type: 'string' },
    Boolean: { type: 'boolean' },
    Date: { type: 'string', format: 'date' },
    DateTime: { type: 'string', format: 'date-time' },
    Mixed: { type: ['string', 'number', 'boolean', 'null'] },
    Null: { type: 'null' },
    Empty: { type: 'null' },
  };

  return typeMapping[inferredType] || { type: 'string' };
}

/**
 * Generates a JSON Schema from profiling results
 */
export function generateJsonSchema(results: ProfileResult, filename: string): JsonSchema {
  const properties: Record<string, JsonSchemaProperty> = {};
  const required: string[] = [];

  for (const col of results.column_profiles) {
    const { inferred_type, count, missing } = col.base_stats;
    const { type, format } = mapDataCertTypeToJsonSchema(inferred_type);

    const property: JsonSchemaProperty = { type };

    // Add format for date types
    if (format) {
      property.format = format;
    }

    // Add numeric constraints if available
    if (col.numeric_stats) {
      const { min, max } = col.numeric_stats;
      if (min !== undefined && min !== null && isFinite(min)) {
        property.minimum = min;
      }
      if (max !== undefined && max !== null && isFinite(max)) {
        property.maximum = max;
      }
    }

    // Add string length constraints if available
    if (inferred_type === 'String') {
      if (col.min_length !== undefined && col.min_length !== null) {
        property.minLength = col.min_length;
      }
      if (col.max_length !== undefined && col.max_length !== null) {
        property.maxLength = col.max_length;
      }
    }

    properties[col.name] = property;

    // Add to required array if 0% null rate
    const nullRate = count > 0 ? missing / count : 0;
    if (nullRate === 0) {
      required.push(col.name);
    }
  }

  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'datacert-generated-schema',
    title: filename,
    description: 'Schema generated by DataCert',
    type: 'object',
    properties,
    required,
  };
}

/**
 * Generates a JSON Schema string with proper formatting
 */
export function generateJsonSchemaReport(results: ProfileResult, filename: string): string {
  const schema = generateJsonSchema(results, filename);
  return JSON.stringify(schema, null, 2);
}
